# Generated by Django 5.2.1 on 2025-06-01 14:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/aprofiles/default_pfp.jpg', null=True, upload_to=accounts.models.upload_to_profile),
        ),
    ]
