# Generated by Django 5.2.1 on 2025-06-09 10:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profiles/default_pic_tb.jpg', null=True, upload_to=accounts.models.upload_to_profile),
        ),
    ]
