# Generated by Django 5.2.1 on 2025-05-29 22:41

import cars.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=cars.models.upload_to_car)),
                ('year', models.PositiveIntegerField()),
                ('region', models.CharField(choices=[('JDM', 'Japanese'), ('GER', 'German'), ('USA', 'American Muscle'), ('KOR', 'Korean'), ('ITA', 'Italian'), ('FRA', 'French'), ('UK', 'British'), ('OTH', 'Other')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=cars.models.upload_to_mod)),
                ('date_installed', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='cars.car')),
            ],
        ),
    ]
